### PR TITLE
Small fixes & remarks about the docs

### PR DESCRIPTION
**Pull request by xdaluca**
I just finished reading the Camino docs, very clear and quite detailed, just had some light wording and grammar edits. Also:
- The "what is Camino?" seems to be very similar to the [avalanche introduction doc](https://docs.avax.network/#introduction) so, I think it probably is best to mention that Camino is a fork of Avalanche in the intro.
- The same goes for the first three titles of the [Camino Platform Overview](https://docs.camino.foundation/about/) very similar to [Avalanche Platform Overview](https://docs.avax.network/overview/getting-started/avalanche-platform).

### CODE REVIEW

**Review by DerTiedemann — APPROVED** [review]
LGTM, thanks for the help :)

**Comment by c4t-ag** [comment]
@xdaluca thx for contributing.
We splitted our pull request workflow into 2 steps.
- PR's go first into dev branch (will be automatically deployed on playground.docs.camino.foundation)
- After review from our staff we merge regulary dev into main.
-> Pls. change the target branch to dev, thx!

**Comment by xdaluca** [comment]
> @xdaluca thx for contributing. We splitted our pull request workflow into 2 steps.
> 
> * PR's go first into dev branch (will be automatically deployed on playground.docs.camino.foundation)
> * After review from our staff we merge regulary dev into main.
>   -> Pls. change the target branch to dev, thx!

@c4t-ag sounds good to me, changed the target branch to dev.

**Review by havan — APPROVED** [review]
Looking good, thanks for your help!

**Pull request merged**
